version: 2.1
 
# Define the jobs we want to run for this project
jobs:
  bump:
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: npm i 
      - run: npm version minor 
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: git push -q https://${GITHUB_TOKEN}@github.com/ssedoudbgouv/CIRCLE_PROJECT_REPONAME.git circleci-project-setup
 

  publish:
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: npm i 
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: cat ~/repo/.npmrc
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - bump:
          filters: 
            branches:
              only:
                - circleci-project-setup   