version: 2.1
 
# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: npm i 
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: echo "this is the build job"
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build